### ISSUE TITLE
fix: ヘッド画像読込時にタイトルがガタつく

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/vuefes-2019#62]
現在、下記のように、ヘッド画像が読み込まれてから、タイトルである「Vue Fes Japan 2019」がカクンと落ちるようになっている。

![vuefes-2019-head](https://user-images.githubusercontent.com/634357/58458695-cac2fd80-8164-11e9-8d90-8f646cb62abb.gif)

これを変更して、ヘッド画像が読み込まれる前からタイトルの位置を、ヘッド画像読み込み後と同じ位置に調整する。

## 参考

Vue Fes Japan 2018 ティザーサイトでは下記のように実装していた。

- https://github.com/kazupon/vuefes/blob/18f11d74db7bda916efb3c7195bb10c982843fe6/src/components/TheHeadImage.vue#L53-L68

```scss
.the-head-image {
  position: relative;
  padding-top: calc((1152 / 768) * 100%);

  @media screen and (min-width: $layout-breakpoint--is-small-up) {
    padding-top: calc((1080 / 1920) * 100%);
  }
}

.head-image {
  position: absolute;
  display: block;
  top: 0;
  left: 0;
  width: 100%;
}
```
